---
# handlers file for apache
#
- name: restart httpd service
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: restart apache2 service
  ansible.builtin.service:
    name: apache2
    state: restarted

